const cards = [
  ["You Are Mine","Reflection","Let the heart become quiet enough to remember that love does not need to possess; it simply remains."],
  ["I Am Watching You","Awareness","Before you speak or act, pause. Let awareness become the gentle witness that guides your next step."],
  ["Do Not Be Afraid","Courage","Fear becomes smaller when we meet the present moment with faith, patience and a steady heart."],
  ["I Am With You","Faith","Even in a difficult hour, remember that you do not have to carry every burden alone."],
  ["Serve Without Waiting","Service","The purest service is often quiet. Do what is needed, and let the act itself be enough."],
  ["Be Still","Peace","When the mind is crowded, silence can reveal what hurried thoughts hide."],
  ["Love All","Love","Let kindness cross the boundaries that the mind creates. Every person deserves dignity."],
  ["I Am Angry With You","Self-reflection","When anger appears, ask what it is trying to protect. Understanding can transform reaction into wisdom."],
  ["Truth Is Simple","Truth","Truth does not need decoration. Speak clearly, live honestly, and let your actions support your words."],
  ["Your Heart Is the Temple","Inner life","Make the heart a place where resentment has less room and compassion has more room."],
  ["Do One Good Thing","Daily practice","A meaningful life is built from ordinary acts repeated with sincerity."],
  ["Do Not Compare","Contentment","Another person's path is not a measurement of yours. Walk your own road with gratitude."],
  ["Forgive","Compassion","Forgiveness does not erase what happened; it releases the heart from carrying it forever."],
  ["Listen First","Wisdom","Sometimes the most loving answer begins by giving another person the space to be heard."],
  ["Work Is Worship","Diligence","Bring care to ordinary work. Attention and sincerity can turn a routine task into an offering."],
  ["Be Kind in Secret","Humility","A good deed becomes especially beautiful when applause is not part of the reason for doing it."],
  ["The Mind Needs Training","Discipline","Thoughts may arrive uninvited, but we can learn which ones deserve our attention."],
  ["Peace Begins Within","Peace","Do not wait for the world to become quiet before choosing a peaceful response."],
  ["Give More Than You Take","Generosity","Ask what you can contribute today, even if the contribution seems small."],
  ["See the Good","Positive vision","Looking for goodness does not deny difficulty; it keeps difficulty from becoming the whole story."],
  ["Humility Opens the Door","Humility","The willingness to say 'I may be wrong' is often the beginning of learning."],
  ["Remember Your Values","Integrity","When circumstances change, values can remain the steady ground beneath your choices."],
  ["Patience Is Strength","Patience","Not every answer arrives immediately. Give good things time to take root."],
  ["Speak Softly","Gentleness","Strength does not require harshness. A calm voice can carry a firm truth."],
  ["Gratitude Changes the Day","Gratitude","Notice one ordinary blessing today. Gratitude teaches the mind to see what it usually overlooks."],
  ["Do Not Carry Yesterday","Release","Learn from yesterday without allowing it to occupy every room in today's mind."],
  ["Help Someone","Service","Look around. There may be a simple need nearby that you can meet without being asked."],
  ["Faith Needs Action","Faith","Faith becomes practical when it changes how we respond, work, forgive and serve."],
  ["The Quiet Voice","Conscience","In the noise of opinions, make time to hear the quiet voice of conscience."],
  ["Love Is a Practice","Love","Love grows through patience, attention, forgiveness and small acts of care."],
  ["Choose the Higher Response","Wisdom","You cannot always choose what happens, but you can pause before choosing how to respond."],
  ["A Smile Is Service","Kindness","A sincere smile can be a small way of telling another person: you are seen."],
  ["Do Not Waste a Moment","Purpose","Use today's ordinary moments well. A meaningful life is not made only of extraordinary days."],
  ["Keep the Heart Clean","Inner life","Release jealousy, resentment and pride before they become habits of the heart."],
  ["Respect Every Person","Dignity","Treat people with dignity even when you disagree. Character shows most clearly in difficult encounters."],
  ["Learn From Everyone","Learning","Every person can teach us something when we approach them without arrogance."],
  ["Be Useful","Service","Ask not only what you want to receive from a day, but what good you can leave in it."],
  ["Silence Is Not Empty","Silence","A quiet moment can be full of insight when we stop trying to fill it."],
  ["Let Go of Praise","Humility","Do the right thing because it is right, not because someone may notice."],
  ["Do Not Feed Anger","Self-control","Anger asks for immediate action. Wisdom asks for one more breath."],
  ["Speak the Truth Kindly","Truth","Truth and kindness need not be opposites. Say what is necessary without making another person smaller."],
  ["The Smallest Service Counts","Service","A cup of water, a patient answer or a helping hand can become meaningful when offered sincerely."],
  ["Walk With Gratitude","Gratitude","There is dignity in appreciating what is already present while continuing to grow."],
  ["Be Present","Awareness","The person in front of you deserves your attention more than the thought waiting in your phone."],
  ["Love Does Not Keep Score","Love","Give without maintaining a private ledger of what you are owed in return."],
  ["A Difficult Person Is a Lesson","Patience","Some encounters test our values. Let the test become an opportunity to practice them."],
  ["Choose Simplicity","Simplicity","A simpler life leaves more room for attention, relationships, service and peace."],
  ["Your Words Matter","Speech","Words can heal or wound. Before speaking, ask whether your words are necessary and kind."],
  ["Do Not Lose Hope","Hope","A difficult season is still a season. Keep taking the next honest step."],
  ["Let Service Lead","Service","When the heart asks how to help, begin with whatever useful thing is within reach."],
  ["Be Equal in Love","Unity","Let your respect for one person teach you to widen respect for many."],
  ["Control Is Freedom","Discipline","Freedom is not doing every impulse. It is being able to choose what deserves action."],
  ["A Pure Intention Matters","Intention","Before an action, examine the motive. A good act becomes stronger when the intention is clean."],
  ["The Best Lesson Is Lived","Practice","People remember what we practice more readily than what we merely explain."],
  ["Do Not Judge Quickly","Compassion","You rarely know the whole story behind another person's behaviour. Leave room for understanding."],
  ["Courage to Apologise","Humility","A sincere apology is not weakness. It is the courage to value truth above ego."],
  ["Make Peace Where You Can","Peace","If one conversation can reduce unnecessary hurt, have the conversation with care."],
  ["Be a Light","Example","You do not have to solve everything to make a difference. Sometimes example is enough."],
  ["Remember the Goal","Purpose","When distractions multiply, return to the values that made the journey meaningful."],
  ["Give Time","Love","Attention is one of the most precious forms of generosity."],
  ["Do Not Fear Silence","Inner life","Silence can feel uncomfortable because it removes distractions. Stay a little longer."],
  ["Let Wisdom Slow You Down","Wisdom","Not every decision needs an immediate answer. A pause can prevent a regret."],
  ["Be Honest With Yourself","Truth","Self-honesty is the beginning of genuine change."],
  ["Respect Your Duties","Responsibility","Small responsibilities performed faithfully build trust in ourselves and with others."],
  ["The Heart Knows Service","Service","When compassion becomes action, service stops being an idea and becomes a way of living."],
  ["Practice Contentment","Contentment","Contentment is not giving up ambition; it is refusing to make peace dependent on having more."],
  ["Forgive Yourself Too","Compassion","Learn from mistakes without turning the lesson into lifelong punishment."],
  ["Do Not Seek Revenge","Peace","Revenge keeps the wound active. Choose the response that protects your dignity without creating more harm."],
  ["Be Patient With Growth","Growth","A seed does not become a tree because we stare at it. Keep watering what matters."],
  ["Give Respect First","Dignity","You can begin with respect even when respect has not yet been returned."],
  ["Make Your Home Peaceful","Peace","The values we practice at home become the values we carry into the world."],
  ["Listen to Conscience","Conscience","When approval and conscience disagree, take time to understand what your deepest values are asking."],
  ["Love Without Fear","Love","Fear asks us to build walls. Love asks us to meet people with discernment and openness."],
  ["A Gentle Mind","Gentleness","Do not make every thought a command. Let the mind become spacious and kind."],
  ["Service Without Status","Service","The worth of service is not measured by position, visibility or applause."],
  ["Truth in Small Things","Integrity","Integrity is built in little choices long before it is tested in big ones."],
  ["Let Gratitude Speak","Gratitude","Tell someone today what you appreciate about them. Gratitude grows when expressed."],
  ["Do Not Chase Every Thought","Awareness","The mind produces many thoughts. You can observe them without following all of them."],
  ["Make Room for Others","Generosity","A generous heart has room for another person's needs, pace and perspective."],
  ["Peace Is a Daily Choice","Peace","Peace is not a permanent mood; it is something we practice again and again."],
  ["Be Faithful to Goodness","Integrity","Stay committed to what is right even when the immediate reward is invisible."],
  ["Do Not Hide Kindness","Kindness","Let kindness become visible enough that someone else learns how to pass it on."],
  ["Learn to Wait","Patience","Waiting can teach us that not every good thing needs to happen on our preferred schedule."],
  ["Let Love Correct You","Love","Real love does not only comfort us; sometimes it asks us to become better."],
  ["Choose Cooperation","Unity","Look for the part of a problem that can be solved together before focusing on differences."],
  ["Be Responsible for Your Peace","Peace","Others may affect your emotions, but you can still take responsibility for your response."],
  ["Do Not Let Ego Drive","Humility","Before insisting on being right, ask whether the relationship or the truth needs something else from you."],
  ["Give Hope","Hope","A hopeful word offered at the right time can become a lifeline for someone who is struggling."],
  ["Serve the Moment","Presence","You do not need a grand opportunity to serve. Serve the moment that is already in front of you."],
  ["Make Learning a Habit","Learning","Keep the mind teachable. Every day can add one small piece to understanding."],
  ["Choose Gratitude Over Complaint","Gratitude","Complaint points toward what is missing; gratitude helps us notice what is still possible."],
  ["Do Not Forget Compassion","Compassion","Being correct is not enough. Ask whether your way of correcting leaves room for dignity."],
  ["Be Consistent","Discipline","Small good habits repeated quietly can shape a life more deeply than occasional bursts of effort."],
  ["A Clean Start","Renewal","Each morning gives you another chance to speak better, act better and serve better."],
  ["Love Your Neighbour","Unity","Care begins close to home. Notice the people around you and respond to real needs."],
  ["Do Not Carry Pride","Humility","Whatever your gifts, remember that growth becomes easier when gratitude travels with ability."],
  ["Speak Less, Do More","Action","Let actions carry some of the message that words cannot."],
  ["Be the Calm Person","Peace","When a room becomes tense, one calm person can change the direction of a conversation."],
  ["Give Without Fear","Generosity","Giving is not always about money. Time, attention, knowledge and patience are gifts too."],
  ["Let the Heart Expand","Love","Make your circle of concern a little wider today."],
  ["Remember the One","Unity","Beneath many names and forms is the shared human longing for love, dignity and peace."],
  ["Walk Gently","Awareness","Move through the world with awareness of how your choices affect people and nature."],
  ["Finish What You Begin","Responsibility","Faithfulness is often less dramatic than inspiration, but it is what turns intention into reality."],
  ["One Good Thought","Mindfulness","You do not need to transform your whole life today. Begin with one thought worth keeping."],
  ["Be Thankful for Teachers","Gratitude","Every teacher, experience and mistake can leave something useful behind."],
  ["Serve With Joy","Service","Service becomes lighter when we stop seeing it as a burden and begin seeing it as participation."],
  ["The Heart Can Change","Hope","A habit formed over years can still be changed one sincere choice at a time."],
  ["Choose Understanding","Compassion","Try to understand before deciding what another person deserves from you."],
  ["End the Day Well","Reflection","Before sleep, remember one thing you learned, one thing you are grateful for and one thing you can improve tomorrow."],
  ["Return to Love","Love","When you are unsure what to do next, return to the values of love, truth, peace and service."],
  ["You Are Not Alone","Faith","Let today's difficulties be met with patience, prayer, friendship and the courage to ask for help."],
  ["I Am Watching You","Awareness","Let the thought of being observed become less about fear and more about living with integrity when nobody is watching."],
  ["You Are Mine","Devotion","Devotion is not possession. It is the quiet feeling of belonging to something greater than the small self."],
  ["Keep Walking","Perseverance","Progress can be slow and still be real. Take the next step with patience."],
  ["Be Love in Action","Service","Let today's love have hands, feet, time and effort."],
  ["One Day at a Time","Presence","You only have to live today's responsibilities today. Tomorrow can wait its turn."],
  ["Peace, My Child","Comfort","When the heart feels tired, choose gentleness. Rest is also part of continuing the journey."],
  ["The Last Card Is Not the End","Reflection","A card can offer a thought, but the real lesson begins when the thought enters ordinary life."]
];

const $ = id => document.getElementById(id);
function dayOfYear(date){const start=new Date(date.getFullYear(),0,0);return Math.floor((date-start)/86400000)}
let dailyIndex = (dayOfYear(new Date())-1) % cards.length;
function renderCard(index){
  const c=cards[index];
  $('dailyTag').textContent=c[1];$('dailyTitle').textContent=c[0];$('dailyText').textContent=c[2];
  $('cardNumber').textContent=`CARD ${String(index+1).padStart(2,'0')} / ${cards.length}`;
  $('dailyIndex').textContent=`${index+1} of ${cards.length}`;
}
function formatDate(){const d=new Date();$('todayDate').textContent=d.toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}
formatDate();renderCard(dailyIndex);
$('nextCard').addEventListener('click',()=>{dailyIndex=(dailyIndex+1)%cards.length;renderCard(dailyIndex)});
$('menuBtn').addEventListener('click',()=>{$('mainNav').classList.toggle('open')});
document.querySelectorAll('#mainNav a').forEach(a=>a.addEventListener('click',()=> $('mainNav').classList.remove('open')));
const stories={
 'two-seeds':['The Two Seeds','Two seeds rested in the same soil. One feared the rain and remained closed; the other opened itself to the unknown. The story is a simple reminder that growth often asks us to accept uncertainty. We cannot control every condition, but we can choose whether to remain closed or take the next step with trust.'],
 'empty-cup':['The Empty Cup','A cup already filled cannot receive another drop. In the same way, a mind crowded with pride may struggle to receive a new lesson. Emptying the cup does not mean knowing nothing; it means becoming willing to learn.'],
 'lamp':['The Lamp','A lamp does not become dim by lighting another lamp. Service can multiply without reducing the light within us. When knowledge, kindness or encouragement is shared sincerely, another person can carry that light forward.']
};
document.querySelectorAll('.read-story').forEach(btn=>btn.addEventListener('click',()=>{const s=stories[btn.dataset.story];$('modalTitle').textContent=s[0];$('modalText').textContent=s[1];$('storyModal').classList.add('open');$('storyModal').setAttribute('aria-hidden','false')}));
function closeModal(){$('storyModal').classList.remove('open');$('storyModal').setAttribute('aria-hidden','true')}
$('modalClose').addEventListener('click',closeModal);document.querySelector('.modal-backdrop').addEventListener('click',closeModal);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
// Keep the daily card stable for the whole day, while the preview button lets visitors browse the booklet.
